# Generated by Django 3.1.1 on 2020-09-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishyojana', '0002_post_add_to_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='emarket'),
        ),
    ]
