# Generated by Django 3.1.1 on 2020-09-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishyojana', '0003_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
    ]
