# Generated by Django 3.1.1 on 2020-09-27 03:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Health_Scheme',
            new_name='Health_Schemes',
        ),
    ]
